[package]
name = "egui_web_new"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { version = "0.29.1", features = ["accesskit", "default_fonts"]}
egui = "0.29.1"
log = "0.4.22"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"